# Generated by Django 5.1.3 on 2025-05-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountHolder', models.CharField(max_length=100)),
                ('AccountType', models.CharField(max_length=100)),
                ('AccountStatus', models.CharField(max_length=100)),
                ('AccountBalance', models.FloatField()),
                ('DateOpened', models.DateTimeField()),
                ('AccountUsername', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Useracc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('passwrd', models.CharField(max_length=100)),
            ],
        ),
    ]
