# Generated by Django 5.1.3 on 2025-05-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='DateOpened',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
