# Generated by Django 5.2.1 on 2025-05-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('browser_info', models.TextField()),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('is_trusted', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('login_count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Bank.useracc')),
            ],
        ),
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('location_data', models.TextField(blank=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bank.devicefingerprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to='Bank.useracc')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_transaction_limit', models.FloatField(default=50000.0)),
                ('single_transaction_limit', models.FloatField(default=25000.0)),
                ('monthly_spending_cap', models.FloatField(default=200000.0)),
                ('security_alerts_enabled', models.BooleanField(default=True)),
                ('login_notifications', models.BooleanField(default=True)),
                ('transaction_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='Bank.useracc')),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('unusual_login', 'Unusual Login Location'), ('high_amount', 'High Amount Transaction'), ('frequent_transactions', 'Frequent Transactions'), ('new_device', 'New Device Login'), ('failed_login', 'Multiple Failed Logins'), ('limit_exceeded', 'Transaction Limit Exceeded')], max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to='Bank.useracc')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daily_spent', models.FloatField(default=0.0)),
                ('monthly_spent', models.FloatField(default=0.0)),
                ('transaction_count', models.IntegerField(default=0)),
                ('last_transaction', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_limits', to='Bank.useracc')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
