# Generated by Django 5.2.1 on 2025-05-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_devicefingerprint_loginactivity_securitysettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('spending_pattern', 'Spending Pattern'), ('budget_recommendation', 'Budget Recommendation'), ('goal_suggestion', 'Goal Suggestion'), ('saving_opportunity', 'Saving Opportunity'), ('risk_alert', 'Risk Alert'), ('achievement', 'Achievement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='Bank.useracc')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='Bank.useracc')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Response'), ('system', 'System Message')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Bank.chatconversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('savings', 'Savings Goal'), ('investment', 'Investment Goal'), ('debt_payoff', 'Debt Payoff'), ('emergency_fund', 'Emergency Fund'), ('vacation', 'Vacation Fund'), ('home', 'Home Purchase'), ('education', 'Education Fund'), ('retirement', 'Retirement Fund'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.FloatField()),
                ('current_amount', models.FloatField(default=0.0)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_suggestions', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to='Bank.useracc')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('food', 'Food & Dining'), ('transportation', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('travel', 'Travel'), ('investment', 'Investment'), ('savings', 'Savings'), ('other', 'Other')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Bank.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('food', 'Food & Dining'), ('transportation', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('travel', 'Travel'), ('investment', 'Investment'), ('savings', 'Savings'), ('other', 'Other')], max_length=20)),
                ('monthly_budget', models.FloatField(default=0.0)),
                ('current_spending', models.FloatField(default=0.0)),
                ('ai_recommended_budget', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='Bank.useracc')),
            ],
            options={
                'unique_together': {('user', 'category_type')},
            },
        ),
    ]
