# Generated by Django 5.2.1 on 2025-06-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_aiinsight_chatconversation_chatmessage_financialgoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Transfer Out', 'Transfer Out'), ('Transfer In', 'Transfer In')], max_length=20)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('recipient_account', models.CharField(blank=True, max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_transactions', to='Bank.account')),
            ],
            options={
                'verbose_name': 'Upcoming Transaction',
                'verbose_name_plural': 'Upcoming Transactions',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
