# Generated by Django 5.2.1 on 2025-06-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_upcomingtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('card_type', models.CharField(choices=[('debit', 'Debit Card'), ('prepaid', 'Prepaid Card')], default='debit', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('daily_limit', models.FloatField(default=25000.0)),
                ('monthly_limit', models.FloatField(default=100000.0)),
                ('online_transactions_enabled', models.BooleanField(default=True)),
                ('international_transactions_enabled', models.BooleanField(default=False)),
                ('contactless_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_cards', to='Bank.account')),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('merchant_category', models.CharField(blank=True, max_length=100)),
                ('transaction_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('declined', 'Declined')], default='success', max_length=10)),
                ('is_online', models.BooleanField(default=True)),
                ('is_international', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_transaction', to='Bank.transaction')),
                ('virtual_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_transactions', to='Bank.virtualcard')),
            ],
        ),
    ]
