# Generated by Django 5.2.1 on 2025-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_virtualcard_cardtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='daily_spent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='virtualcard',
            name='last_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualcard',
            name='monthly_spent',
            field=models.FloatField(default=0.0),
        ),
    ]
