# Generated by Django 5.2.1 on 2025-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_rename_timezone_devicefingerprint_user_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Transfer Out', 'Transfer Out'), ('Transfer In', 'Transfer In'), ('Virtual Card Transfer', 'Virtual Card Transfer'), ('Virtual Card Withdraw', 'Virtual Card Withdraw')], max_length=30),
        ),
    ]
