# Generated by Django 5.2.1 on 2025-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0011_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
